input = input.txt
output = output.txt

main:
	flex task1.l
	gcc lex.yy.c
	./a.exe <input1.txt> output1.txt
	./a.exe <input2.txt> output2.txt
	./a.exe <input3.txt> output3.txt
	./a.exe <input4.txt> output4.txt
	./a.exe <input5.txt> output5.txt
