input = input.txt
output = output.txt

main:
	flex task1.l
	gcc lex.yy.c -o task1
	./task1 < input1.txt > output1.txt
	./task1 < input2.txt > output2.txt
	./task1 < input3.txt > output3.txt
	./task1 < input4.txt > output4.txt
	./task1 < input5.txt > output5.txt